### ISSUE TITLE
app submodule in gh-pages branch?

### ISSUE THREAD

**Issue by kirschbombe** [kirschbombe/mapsandtexts#15]
The gh-pages branch doesn't seem to be up-to-date - is that bc it's not pulling in the app submodule?

**Comment by ghost** [comment]
The gh-pages branch hadn't been set up initially to point to the `dist` branch for the code and stylesheets. I have updated it to use a submodule, pointing to the app/ dir, and have updated the configuration files to work with the most recent version of the application in the `dist` branch.
