### ISSUE TITLE
improve error handling for data passed to libraries

### ISSUE THREAD

**Issue by ghost** [kirschbombe/mapsandtexts#23]
When incomplete or ill-formed data is passed to libraries (e.g., Leaflet), error handling in the application is not sufficiently robust to prevent the application from crashing. A couple of improvements: 
- add load-time checks/assertions to prevent issues with data (article files) from being propagated further in the app
- present useful debugging information when checks aren't properly passed
- ensure that all calls to library functions have sufficient error handling and recovery

Recently, the absence of a try-catch around this call (or not identifying an issue with the data)

  https://github.com/kirschbombe/boulevardier/blob/master/app/js/views/marker.js#L32

caused the page load to fail, due to a single formatting issue in an article.

**Comment by kirschbombe** [comment]
Update: page load fails even when all formatting issues are resolved in the xml. This only happens when loading new articles. Once the new article is removed from site.json, the content loads. Adding a new article, even one that worked previously, results in page load errors.

**Comment by ghost** [comment]
I cannot reproduce what you describe locally, although I may be misunderstanding the issue. Can you clear your browser's cache and reload with the updated files in place?
I will look into whether there is a way to adjust page expiry settings using Github pages.

**Comment by ghost** [comment]
I have opened two PR's (24, 25) that improve error-reporting when the application is loading and processing articles and config files.

Whenever malformed inputs are encountered, by an XML or JSON parser or by the Leaflet library, there will be an message window indicating the cause of the error. I tested this against XML well-formedness issues, non-existant XML files referenced in the config file, and malformed latitude/longitude values in the articles that would cause issues in Leaflet.

**Comment by ghost** [comment]
It appears that resources delivered by GH Pages are set to expire after 10 min:
```
Cache-Control: max-age=600
```
so I doubt browser caching was causing different results after all.

I think this item can be closed, since the updates in PR 24 and PR 25 have resolved the issue.
