### ISSUE TITLE
Need sticky footer area in title page for colophon information

### ISSUE THREAD

**Issue by kirschbombe** [kirschbombe/mapsandtexts#7]
Added text to the Literary Paris title page attributing credit for the framework (Maps & Texts) and the map marker icon (NounProject). Would prefer if this info were anchored to the bottom. Right now it's in the main div with the title, etc.

**Comment by ghost** [comment]
Added a `pages/` stylesheet to handle footer position:

https://github.com/kirschbombe/literaryparis/pull/2
